export enum TodosTypes {
  TASK = "TASK",
  BUG = "BUG"
}

interface Iuser {
  id: number,
  name: string,
  position: string
}

export const todos = {
  todos: [
    {
      id: 1,
      summary: "Do something nice for someone I care about",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 2,
      summary: "Memorize the fifty states and their capitals",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 3,
      summary: "Watch a classic movie",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 4,
      summary: "Contribute code or a monetary donation to an open-source software project",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 5,
      summary: "Solve a Rubik's cube",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 6,
      summary: "Bake pastries for me and neighbor",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 7,
      summary: "Go see a Broadway production",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 8,
      summary: "Write a thank you letter to an influential person in my life",
      description: "TEST",
      type: TodosTypes.BUG,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 9,
      summary: "Invite some friends over for a game night",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 10,
      summary: "Have a football scrimmage with some friends",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 11,
      summary: "Text a friend I haven't talked to in a long time",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 12,
      summary: "Organize pantry",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 13,
      summary: "Buy a new house decoration",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 14,
      summary: "Plan a vacation I've always wanted to take",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 15,
      summary: "Clean out car",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 16,
      summary: "Draw and color a Mandala",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 17,
      summary: "Create a cookbook with favorite recipes",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 18,
      summary: "Bake a pie with some friends",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 19,
      summary: "Create a compost pile",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 20,
      summary: "Take a hike at a local parK",
      status: "TODO",
      pubDate: "21.01.2024",
      description: "TEST",
      type: TodosTypes.TASK,
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 21,
      summary: "Take a class at local community center that interests you",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 22,
      summary: "Research a topic interested in",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 23,
      summary: "Plan a trip to another country",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 24,
      summary: "Improve touch typing",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 25,
      summary: "Learn Express.js",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 26,
      summary: "Learn calligraphy",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 27,
      summary: "Have a photo session with some friends",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 28,
      summary: "Go to the gym",
      description: "TEST",
      type: TodosTypes.TASK,
      status: "DONE",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 29,
      summary: "Make own LEGO creation",
      description: "TEST",
      type: TodosTypes.BUG,
      status: "TODO",
      pubDate: "21.01.2024",
      reporterId: 1,
      assigneeId: 1,
    },
    {
      id: 30,
      summary: "Изучить реакт",
      status: "TODO",
      pubDate: "21.01.2024",
      description: "TEST",
      type: TodosTypes.BUG,
      reporterId: 1,
      assigneeId: 1,
    },
  ],
  total: 150,
  skip: 0,
  limit: 30,
};
